name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup NodeJs 16.x
        uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
